server:
  port: 8083
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://172.26.223.28:3306/order?useUnicode=true&characterEncoding=utf8
        username: mysqladmin
        password: MPadmin
    application:
      name: order-service

mybatis:
  type-aliases-package: com.rains.transaction.tx.dubbo.sample.order.api.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.rains.bonuspoint: info
        com.rains.lottery: debug
        com.rains: debug
        io.netty: info

    path: "./logs"

# Base packages to scan Dubbo Components (e.g @Service , @Reference)
dubbo:
  scan:
    basePackages: com.rains.transaction.tx.dubbo.sample
  # Dubbo Config properties
  ## ApplicationConfig Bean
  application:
    id: dubbo-order
    name: dubbo-order
    qosEnable: false
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: -1
    accesslog: true
  #    status: server
  ## RegistryConfig Bean
  registry:
    id: my-registry
    address: zookeeper://172.26.223.27:2181?client=curator
  # N/A

endpoints:
  health:
    sensitive: false
  dubbo:
    enabled: false